// Generated by CoffeeScript 1.6.3
/*
# nodejs-express-mongoose-demo
# Copyright(c) 2013 Madhusudhan Srinivasa <madhums8@gmail.com>
# MIT Licensed
*/


(function() {
  var app, config, env, exports, express, fs, mongoose, port;

  express = require('express');

  fs = require('fs');

  env = process.env.NODE_ENV || 'development';

  config = require('./config/config')[env];

  mongoose = require('mongoose');

  mongoose.connect(config.db);

  require("./models/ticket");

  app = express();

  require('./config/express')(app, config);

  require('./config/routes')(app);

  port = process.env.PORT || 3456;

  app.listen(port);

  console.log("Ticket System app started on port " + port);

  exports = module.exports = app;

}).call(this);
