// Generated by CoffeeScript 1.6.3
(function() {
  var DEFAULT_BASIC_AUTH, PATH, TicketManager, assert, env, request;

  assert = require("assert");

  env = process.env.NODE_ENV || 'development';

  DEFAULT_BASIC_AUTH = require('./config/config')[env]['basicAuth'];

  request = require("request");

  PATH = "/api/tickets/new";

  TicketManager = (function() {
    function TicketManager(name, host, basicAuth) {
      this.name = name;
      this.host = host;
      assert(this.name, "missing name");
      assert(this.host, "missing host");
      this.basicAuth = basicAuth || DEFAULT_BASIC_AUTH;
      this.debuglog = require("debug")("ticketman:TicketManager#" + name);
    }

    TicketManager.prototype.issue = function(title, category, content, callback) {
      var options;
      options = {
        method: 'POST',
        url: "" + this.host + PATH,
        auth: this.basicAuth,
        json: {
          title: title,
          owner_id: this.name,
          category: category,
          content: content
        }
      };
      return request(options, function(err, res, body) {
        if (err != null) {
          return callback(err);
        }
        if (res.statusCode !== 200) {
          return callback(new Error("fail to issue ticket:" + title + "#" + category + ". server reponse:" + res.statusCode));
        }
        if (body._id != null) {
          body.id = body._id;
        }
        callback(null, body);
      });
    };

    return TicketManager;

  })();

  module.exports = TicketManager;

}).call(this);
