// Generated by CoffeeScript 1.6.3
(function() {
  var TicketManager;

  TicketManager = (function() {
    function TicketManager() {}

    return TicketManager;

  })();

  module.exports = TicketManager;

}).call(this);
