// Generated by CoffeeScript 1.6.3
(function() {
  var Ticket, mongoose;

  mongoose = require('mongoose');

  Ticket = mongoose.model('Ticket');

  exports.index = function(req, res, next) {
    Ticket.find({}, function(err, tickets) {
      if (err != null) {
        return next(err);
      }
      res.render('tickets/index', {
        title: 'All Tickets',
        tickets: tickets
      });
    });
  };

}).call(this);
