// Generated by CoffeeScript 1.6.3
(function() {
  var Ticket, mongoose;

  mongoose = require('mongoose');

  Ticket = mongoose.model('Ticket');

  exports.index = function(req, res, next) {
    Ticket.find({}, function(err, tickets) {
      if (err != null) {
        return next(err);
      }
      res.render('tickets/index', {
        title: 'All Tickets',
        tickets: tickets
      });
    });
  };

  exports.show = function(req, res, next) {
    var id;
    id = String(req.params.id || '');
    if (id == null) {
      return next();
    }
    Ticket.findById(id, function(err, ticket) {
      if (err != null) {
        return next(err);
      }
      res.render('tickets/show', {
        title: 'All Tickets',
        ticket: ticket
      });
    });
  };

  exports.create = function(req, res, next) {
    var ticket,
      _this = this;
    ticket = new Ticket(req.body);
    Ticket.save(function(err) {
      if (err != null) {
        return next(err);
      }
      return res.json(ticket);
    });
  };

  exports.assign = function(req, res, next) {
    Ticket.arrangeAssignment(req.body, function(err, ticket) {
      if (err != null) {
        return next(err);
      }
      if (ticket == null) {
        return next();
      }
      return res.json(ticket);
    });
  };

  exports.comment = function(req, res, next) {};

  exports.complete = function(req, res, next) {};

  exports.giveup = function(req, res, next) {};

}).call(this);
