// Generated by CoffeeScript 1.6.3
(function() {
  var express, flash, mongoStore, path;

  express = require('express');

  mongoStore = require('connect-mongo')(express);

  flash = require('connect-flash');

  path = require("path");

  module.exports = function(app, config, passport) {
    var pathToView;
    app.set('showStackError', true);
    app.use(express.compress({
      filter: function(req, res) {
        return /json|text|javascript|css/.test(res.getHeader('Content-Type'));
      },
      level: 9
    }));
    app.use(express["static"](config.root + '/public'));
    if (process.env.NODE_ENV !== 'test') {
      app.use(express.logger('dev'));
    }
    pathToView = path.join(config.root, '/views');
    console.log("[express::main] pathToView:" + pathToView);
    app.set('views', config.root + '/views');
    app.set('view engine', 'jade');
    return app.configure(function() {
      app.use(express.cookieParser());
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      app.use(express.session({
        secret: 'fasr_42*@3paskr$2LQRkvQ',
        store: new mongoStore({
          url: config.db,
          collection: 'sessions'
        })
      }));
      app.use(flash());
      app.use(app.router);
      app.use(function(err, req, res, next) {
        if (~err.message.indexOf('not found')) {
          return next();
        }
        console.error(err.stack);
        return res.status(500).render('500', {
          error: err.stack
        });
      });
      app.use(function(req, res, next) {
        return res.status(404).render('404', {
          url: req.originalUrl,
          error: 'Not found'
        });
      });
      return app.locals({
        VERSION: Date.now().toString(36),
        APP_NAME: config.app.name
      });
    });
  };

}).call(this);
