// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app, passport, auth) {
    var home;
    home = require("../controllers/home");
    return app.get('/', home.index);
  };

}).call(this);
