// Generated by CoffeeScript 1.6.3
(function() {
  var m;

  m = require("../middleware");

  module.exports = function(app, passport, auth) {
    var controller;
    controller = require("../controllers/ticket");
    app.get('/', controller.index);
    app.get('/tickets', controller.index);
    app.get('/tickets/:id', controller.show);
    app.post('/tickets/:id/abandon', controller.abandon);
    app.post('/tickets/:id/comment', controller.adminComment);
    app.post('/api/tickets/new', controller.create);
    app.put('/api/tickets/assign', m.authWorker, controller.assign);
    app.put('/api/tickets/:id/comment', m.authWorker, m.updateiWorkerAt, controller.comment);
    app.put('/api/tickets/:id/complete', m.authWorker, controller.complete);
    app.put('/api/tickets/:id/giveup', m.authWorker, controller.giveup);
    controller = require("../controllers/worker");
    app.get('/workers.:format?', controller.index);
    return app.post('/workers/new.:format?', controller.create);
  };

}).call(this);
