// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app, passport, auth) {
    var controller;
    controller = require("../controllers/ticket");
    app.get('/', controller.index);
    app.get('/tickets', controller.index);
    app.get('/tickets/:id', controller.show);
    app.put('/api/tickets/assign', controller.assign);
    app.post('/api/tickets/new', controller.create);
    app.put('/api/tickets/:id/comment', controller.comment);
    app.put('/api/tickets/:id/complete', controller.complete);
    return app.put('/api/tickets/:id/giveup', controller.giveup);
  };

}).call(this);
