// Generated by CoffeeScript 1.8.0
(function() {
  var STATUS, Ticket, mongoose, start, _removeCompleted;

  mongoose = require('mongoose');

  Ticket = mongoose.model('Ticket');

  STATUS = require("../enums/ticket_status");

  _removeCompleted = function(callback) {
    Ticket.removeByStatus(STATUS.COMPLETE, callback);
  };

  start = function() {
    return setTimeout(function() {
      return _removeCompleted(function(err) {
        if (err != null) {
          console.error("clear_db::removeCompleted ERROR: " + err);
        }
        return start();
      });
    }, 7200000);
  };

  start();

}).call(this);
