// Generated by CoffeeScript 1.7.1
(function() {
  var STATUS, Ticket, mongoose, start, start2, _removeAbandoned, _removeCompleted;

  mongoose = require('mongoose');

  Ticket = mongoose.model('Ticket');

  STATUS = require("../enums/ticket_status");

  _removeCompleted = function(callback) {
    Ticket.removeByStatus(STATUS.COMPLETE, callback);
  };

  _removeAbandoned = function(callback) {
    Ticket.removeByStatus(STATUS.ABANDON, callback);
  };

  start = function() {
    return setTimeout(function() {
      return _removeCompleted(function(err) {
        if (err != null) {
          console.error("clear_db::removeCompleted ERROR: " + err);
        }
        return start();
      });
    }, 7200000);
  };

  start2 = function() {
    return setTimeout(function() {
      return _removeAbandoned(function(err) {
        if (err != null) {
          console.error("clear_db::removeAbandoned ERROR: " + err);
        }
        return start2();
      });
    }, 28800000);
  };

  start();

  start2();

}).call(this);
