// Generated by CoffeeScript 1.8.0
(function() {
  var makeSignature, makeSignatureHeader, signer;

  signer = require("oauth-sign");

  makeSignature = function(consumerId, httpMethod, base_uri, params, consumerSecret) {
    return "Ticketman " + consumerId + ":" + (signer.hmacsign(httpMethod, base_uri, params, consumerSecret));
  };

  makeSignatureHeader = function(consumerId, httpMethod, base_uri, params, consumerSecret) {
    return {
      "Ticketman-Authenticate": makeSignature(consumerId, httpMethod, base_uri, params, consumerSecret)
    };
  };

  exports.verify = function(signature, httpMethod, base_uri, params, consumerSecret) {
    return signature === signer.hmacsign(httpMethod, base_uri, params, consumerSecret);
  };

  exports.makeSignature = makeSignature;

  exports.makeSignatureHeader = makeSignatureHeader;

}).call(this);
