// Generated by CoffeeScript 1.6.3
(function() {
  var TICKET_STATUS_TO_INFO_TYPE, helpers, _;

  _ = require("underscore");

  TICKET_STATUS_TO_INFO_TYPE = {
    pending: 'info',
    processing: 'primary',
    completed: 'success',
    abandoned: 'danger'
  };

  helpers = {
    generateDownloadPathByJson: function(jsonId) {
      return "/assets/json/" + jsonId + ".json";
    },
    genDownloadTagByJsonId: function(jsonId, title) {
      var url;
      url = helpers.generateDownloadPathByJson(jsonId);
      return "<a href='" + url + "' class='btn btn-link'><i class='glyphicon glyphicon-download-alt'> </i> " + (title || jsonId) + "</a>";
    },
    genDateTag: function(date) {
      var dateStr, isoStr;
      isoStr = date instanceof Date ? date.toISOString() : date;
      dateStr = date instanceof Date ? date.toDateString() : date;
      return "<small title='" + isoStr + "' class='muted timeago'>" + dateStr + "</small>";
    },
    genPagination: function(pageData) {
      return pagination.create('search', pageData).render();
    },
    genLabelByStatus: function(status) {
      return "<span class='label label-" + (TICKET_STATUS_TO_INFO_TYPE[status] || 'default') + "'>" + status + "</span>";
    }
  };

  module.exports = helpers;

}).call(this);
