// Generated by CoffeeScript 1.6.3
/*
# test for mock_tickets
*/


(function() {
  var mock_tickets, should;

  should = require("should");

  mock_tickets = require("../mock_tickets");

  describe("test mock_tickets", function() {
    before(function() {});
    return describe("mock_tickets", function() {
      return it("should", function() {});
    });
  });

}).call(this);
