// Generated by CoffeeScript 1.6.3
/*
# test for mock_tickets
*/


(function() {
  var TicketManager, async, config, debuglog, request, should, ticketManager;

  should = require("should");

  TicketManager = require("../").TicketManager;

  debuglog = require("debug")("ticketman:test:ticket_manager_test");

  config = require("../config/config")['development'];

  request = require("request");

  async = require("async");

  ticketManager = new TicketManager("test ticket_manager", "http://localhost:3456");

  describe("mock ", function() {
    this.timeout(10 * 60 * 1000);
    return it("should mock 100 tickets", function(done) {
      var arr, content, i, iterator, _i;
      content = {
        detailed: "content of ticket",
        mixed: ["data"]
      };
      arr = [];
      for (i = _i = 0; _i <= 100; i = ++_i) {
        arr.push(i);
      }
      iterator = function(item, callback) {
        var now;
        now = Date.now();
        return ticketManager.issue("mock ticket " + (now.toString(36)) + "-" + item, (now >> 8).toString(36), content, callback);
      };
      return async.each(arr, iterator, done);
    });
  });

}).call(this);
