// Generated by CoffeeScript 1.8.0

/*
 * test for mock_workers
 */

(function() {
  var HOST, TicketWorker, async, config, debuglog, request, should;

  should = require("should");

  TicketWorker = require("../").TicketWorker;

  debuglog = require("debug")("ticketman:test:ticket_worker_test");

  config = require("../config/config")['development'];

  request = require("request");

  async = require("async");

  HOST = "http://localhost:3456";

  describe("mock ", function() {
    this.timeout(10 * 60 * 1000);
    return it("should mock 100 workers", function(done) {
      var arr, i, options, _i;
      options = {
        method: 'POST',
        url: "" + HOST + "/workers/new.json",
        auth: config.basicAuth,
        json: {
          name: "test-" + (Date.now().toString(36)),
          desc: "just for test"
        }
      };
      arr = [];
      for (i = _i = 0; _i <= 100; i = ++_i) {
        arr.push(i);
      }
      return async.each(arr, (function(i, cb) {
        return (options.json.name += i) && request(options, cb);
      }), done);
    });
  });

}).call(this);
