// Generated by CoffeeScript 1.6.3
/*
# test for ticket_worker
*/


(function() {
  var HOST, TicketWorker, WORKER_RECORD, assert, config, debuglog, request, setTicketWorker, should, ticketWorker;

  should = require("should");

  request = require("request");

  TicketWorker = require("../ticket_worker");

  debuglog = require("debug")("ticketman:test:ticket_worker_test");

  assert = require("assert");

  config = require("../config/config")['development'];

  WORKER_RECORD = null;

  ticketWorker = null;

  setTicketWorker = function(val) {
    return ticketWorker = val;
  };

  HOST = "http://localhost:3456";

  describe("test ticket_worker", function() {
    before(function(done) {
      var options;
      options = {
        method: 'POST',
        url: "" + HOST + "/workers/new.json",
        auth: config.basicAuth,
        json: {
          name: "test#" + (Date.now().toString(36)),
          desc: "just for test"
        }
      };
      return request(options, function(err, res, body) {
        debuglog("err:" + err + ", res.statusCode:" + res.statusCode + ", body:%j", body);
        assert.equal(err, null);
        assert.equal(res.statusCode, 200);
        assert.notEqual(body, null);
        body.id = body._id;
        WORKER_RECORD = body;
        WORKER_RECORD.host = HOST;
        WORKER_RECORD.basicAuth = config.basicAuth;
        WORKER_RECORD.category = "sample";
        ticketWorker = new TicketWorker(WORKER_RECORD);
        return done();
      });
    });
    return describe("ticket_worker", function() {
      return it("requireTicket", function(done) {
        console.log("[ticket_worker_test::method] 2 ticketWorker:%j", ticketWorker);
        return ticketWorker.requireTicket(function(err, ticket) {
          should.not.exist(err);
          return done();
        });
      });
    });
  });

}).call(this);
