// Generated by CoffeeScript 1.8.0

/*
 * test for models_ticket
 */

(function() {
  var SAMPLE_CONTENT_1, SAMPLE_TITLE_1, SAMPLE_TITLE_2, STATUS, Ticket, config, debuglog, mongoose, should, _;

  should = require("should");

  _ = require("underscore");

  debuglog = require("debug")("ticketman:test:ticket_test");

  STATUS = require("../enums/ticket_status");

  config = require("../config/config")['development'];

  mongoose = require('mongoose');

  mongoose.connect(config.db);

  mongoose.set('debug', true);

  require("../models/ticket");

  Ticket = mongoose.model('Ticket');

  SAMPLE_TITLE_1 = "test models/ticket 1";

  SAMPLE_TITLE_2 = "test models/ticket 2";

  SAMPLE_CONTENT_1 = {
    itema: "is string",
    itemb: {
      sub: "content",
      sub2: "still"
    },
    itemc: [1, 2, "three"],
    itemd: true
  };

  describe("test", function() {
    after(function(done) {
      return mongoose.connection.db.dropCollection('tickets', done);
    });
    return describe("models/ticket", function() {
      it("should able create doc", function(done) {
        var ticket;
        ticket = new Ticket({
          title: SAMPLE_TITLE_1,
          owner_id: 'test',
          category: 'test',
          content: SAMPLE_CONTENT_1
        });
        return ticket.save(function(err) {
          should.not.exist(err);
          ticket = new Ticket({
            title: SAMPLE_TITLE_2,
            owner_id: 'test',
            category: 'test',
            content: SAMPLE_CONTENT_1
          });
          return ticket.save(function(err) {
            should.not.exist(err);
            return done();
          });
        });
      });
      it("should not allow alive ticket with duplicated title", function(done) {
        var ticket;
        ticket = new Ticket({
          title: SAMPLE_TITLE_1,
          owner_id: 'test',
          category: 'test',
          content: SAMPLE_CONTENT_1
        });
        return ticket.save(function(err) {
          debuglog("[models_ticket_test] err:" + err);
          should.exist(err);
          return done();
        });
      });
      it("should able to complete ticket", function(done) {
        return Ticket.changeStatus({
          title: SAMPLE_TITLE_1
        }, STATUS.COMPLETE, function(err, ticket) {
          debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
          should.not.exist(err);
          should.exist(ticket);
          ticket.status.should.eql(STATUS.COMPLETE);
          return done();
        });
      });
      it("should not abandon a completed ticket", function(done) {
        return Ticket.changeStatus({
          title: SAMPLE_TITLE_1
        }, STATUS.ABANDON, function(err, ticket) {
          debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
          should.not.exist(ticket);
          return done();
        });
      });
      it("should able to process a pending ticket", function(done) {
        return Ticket.changeStatus({
          title: SAMPLE_TITLE_2
        }, STATUS.PROCESSING, function(err, ticket) {
          debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
          should.not.exist(err);
          should.exist(ticket);
          ticket.status.should.eql(STATUS.PROCESSING);
          ticket.title.should.eql(SAMPLE_TITLE_2);
          return done();
        });
      });
      it("should able to add comment to a ticket", function(done) {
        return Ticket.findOne({
          title: SAMPLE_TITLE_2
        }, function(err, ticket) {
          var comment;
          debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
          should.not.exist(err);
          should.exist(ticket);
          comment = {
            name: "worker",
            kind: "info",
            content: "test comment"
          };
          return Ticket.addComment(ticket.id, comment, function(err, ticket) {
            debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
            should.not.exist(err);
            should.exist(ticket);
            _.last(ticket.comments).content.should.eql(comment.content);
            return done();
          });
        });
      });
      it("arrange nothing when no avaliable ticket", function(done) {
        var workerOptions;
        workerOptions = {
          worker: "assignment worker",
          category: "assignment"
        };
        return Ticket.arrangeAssignment(workerOptions, function(err, ticket) {
          debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
          should.not.exist(err);
          should.not.exist(ticket);
          return done();
        });
      });
      it("arrange assignment", function(done) {
        var ticket;
        ticket = new Ticket({
          title: "for assignment 01",
          owner_id: 'test',
          category: 'assignment',
          content: "for assignment 01"
        });
        return ticket.save(function(err, ticket) {
          debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
          should.not.exist(err);
          ticket = new Ticket({
            title: "for assignment 02",
            owner_id: 'test',
            category: 'assignment',
            content: "for assignment 02"
          });
          return ticket.save(function(err, ticket) {
            debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
            should.not.exist(err);
            ticket = new Ticket({
              title: "for assignment 03",
              owner_id: 'test',
              category: 'assignment',
              content: "for assignment 03"
            });
            return ticket.save(function(err, ticket) {
              var workerOptions;
              debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
              should.not.exist(err);
              workerOptions = {
                worker: "assignment worker",
                category: "assignment"
              };
              return Ticket.arrangeAssignment(workerOptions, function(err, ticket) {
                debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
                should.not.exist(err);
                should.exist(ticket);
                ticket.status.should.eql(STATUS.PROCESSING);
                ticket.title.should.eql("for assignment 01");
                return done();
              });
            });
          });
        });
      });
      return it("always arrange eldest assignment", function(done) {
        var workerOptions;
        workerOptions = {
          worker: "assignment worker",
          category: "assignment"
        };
        return Ticket.arrangeAssignment(workerOptions, function(err, ticket) {
          debuglog("[models_ticket_test] err:" + err + ", ticket:%j", ticket);
          should.not.exist(err);
          should.exist(ticket);
          ticket.title.should.eql("for assignment 02");
          ticket.status.should.eql(STATUS.PROCESSING);
          return done();
        });
      });
    });
  });

}).call(this);
